name: test.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  test:
      
    permissions:
      contents: read
      id-token: write  # Required for OIDC
      packages: write  # Required for GitHub Packages

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm
      run: npm install -g npm@latest

    - name: Install dependencies
      run: npm i

    - name: Global install package CLI version
      run: npm i -g .

    - name: Test CLI load first 4 pairs from Uniswap V3 using 2 workers
      run: uniswap-v3-loader --to=3 --multicall_size=2 --workers=2

    - name: Run ESM tests
      run: npm run test-esm

    - name: Run tests with coverage
      run: |
        node --experimental-test-coverage --test \
          --test-reporter=spec --test-reporter-destination=stdout \
          --test-reporter=lcov --test-reporter-destination=lcov.info \
          test/test*.js

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: lcov.info

